spring.application.name=linguist

spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=linguist_db;encrypt=true;trustServerCertificate=true

spring.datasource.username=sa
spring.datasource.password=123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true